#!/bin/bash

# scripts/compound/auto-compound.sh
# Runs at 11:00 PM to implement top priority
# Creates PRD, breaks into tasks, implements, and creates PR

set -e

PROJECT_DIR="$HOME/projects/capgemini-proposal-generator"
LOG_FILE="$PROJECT_DIR/logs/auto-compound-$(date +%Y%m%d).log"
PRIORITIES_FILE="$PROJECT_DIR/reports/priorities.md"

echo "=== Auto-Compound Started: $(date) ===" | tee -a "$LOG_FILE"

cd "$PROJECT_DIR"

# Fetch latest (including tonight's AGENTS.md updates)
git fetch origin main 2>&1 | tee -a "$LOG_FILE"
git checkout main 2>&1 | tee -a "$LOG_FILE"
git pull origin main 2>&1 | tee -a "$LOG_FILE"

# Check if there are priorities to work on
if [ ! -f "$PRIORITIES_FILE" ]; then
    echo "No priorities file found. Skipping." | tee -a "$LOG_FILE"
    exit 0
fi

# Extract the top priority (Priority 1) from the file
TOP_PRIORITY=$(grep -A 20 "### Priority 1:" "$PRIORITIES_FILE" | head -25)

if [ -z "$TOP_PRIORITY" ]; then
    echo "No Priority 1 found. Skipping." | tee -a "$LOG_FILE"
    exit 0
fi

echo "Top Priority Found:" | tee -a "$LOG_FILE"
echo "$TOP_PRIORITY" | tee -a "$LOG_FILE"

# Extract branch name from priority
BRANCH_NAME=$(echo "$TOP_PRIORITY" | grep "Branch:" | sed 's/.*`\(.*\)`.*/\1/' | head -1)

if [ -z "$BRANCH_NAME" ]; then
    BRANCH_NAME="auto-compound-$(date +%Y%m%d)"
fi

echo "Using branch: $BRANCH_NAME" | tee -a "$LOG_FILE"

# Create feature branch
git checkout -b "$BRANCH_NAME" 2>&1 | tee -a "$LOG_FILE" || git checkout "$BRANCH_NAME" 2>&1 | tee -a "$LOG_FILE"

# Run the implementation loop
echo "Starting implementation loop..." | tee -a "$LOG_FILE"
"$PROJECT_DIR/scripts/compound/loop.sh" 15 2>&1 | tee -a "$LOG_FILE"

# Check if there are changes to commit
if git diff --quiet && git diff --staged --quiet; then
    echo "No changes to commit. Cleaning up." | tee -a "$LOG_FILE"
    git checkout main 2>&1 | tee -a "$LOG_FILE"
    git branch -D "$BRANCH_NAME" 2>&1 | tee -a "$LOG_FILE" || true
    exit 0
fi

# Push and create PR
git push -u origin "$BRANCH_NAME" 2>&1 | tee -a "$LOG_FILE"

# Create PR using gh CLI
PR_TITLE="Auto-compound: $(echo "$TOP_PRIORITY" | grep "### Priority" | sed 's/### Priority [0-9]*: //' | head -1)"
PR_BODY="## Auto-Generated PR

This PR was automatically generated by the compound engineering loop.

### Priority Addressed
\`\`\`
$TOP_PRIORITY
\`\`\`

### Changes
$(git log main.."$BRANCH_NAME" --oneline)

---
*Generated at $(date) by auto-compound.sh*"

gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main 2>&1 | tee -a "$LOG_FILE" || echo "PR creation failed or already exists" | tee -a "$LOG_FILE"

echo "=== Auto-Compound Completed: $(date) ===" | tee -a "$LOG_FILE"
